# Vagrantfile for Multi-VM setup with private IPs and provisioning

Vagrant.configure("2") do |config|
    # VM 1: web01 with Ubuntu 20.04
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64" # Ubuntu 20.04
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.101"
      web01.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  
    # VM 2: web02 with Ubuntu 20.04
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/focal64" # Ubuntu 20.04
      web02.vm.hostname = "web02"
      web02.vm.network "private_network", ip: "192.168.56.102"
      web02.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  
    # VM 3: db01 with CentOS Stream 9
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/stream9" # CentOS Stream 9
      db01.vm.hostname = "db01"
      db01.vm.network "private_network", ip: "192.168.56.103"
  
      db01.vm.provider "virtualbox" do |vb|
        vb.memory = "1600"
        vb.cpus = 2
      end
  
      # Provisioning script
      db01.vm.provision "shell", inline: <<-SHELL
        yum install wget unzip mariadb-server -y
        systemctl enable mariadb
        systemctl start mariadb
      SHELL
    end
  end
  